Exclude logback from micrometer-docs-generator
Eliminates java.lang.NoSuchMethodError: 'java.lang.ClassLoader ch.qos.logback.core.util.Loader.systemClassloaderIfNull(java.lang.ClassLoader)' when newer versions of logback are used