Remove Hc5 classes from FeignHttpClientProperties to avoid NoClassDefFoundError. Add more tests to make sure nothing break when Hc5 is missing from the classpath.